source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.1.0'

gem 'rails', '~> 7.1.0'
gem 'puma', '>= 5.0'
gem 'sqlite3', '~> 1.6'
gem 'rack-cors'
gem 'jbuilder'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end
